### ISSUE TITLE
Build error on Mac OS X 10.6.6 x86_64

### ISSUE THREAD

**Issue by avalentino** [bcdev/epr-api#4]
Build on Mac OS X 10.6.6 x86_64 (Snow Leopard) fails with the following message message:

```
ld -dylib -o build/release/libepr_api.dylib ./build/release/epr_api.o ./build/release/epr_core.o
./build/release/epr_dddb.o ./build/release/epr_product.o ./build/release/epr_dataset.o 
./build/release/epr_string.o ./build/release/epr_ptrarray.o ./build/release/epr_field.o 
./build/release/epr_record.o ./build/release/epr_param.o ./build/release/epr_dsd.o 
./build/release/epr_msph.o ./build/release/epr_swap.o ./build/release/epr_band.o 
./build/release/epr_bitmask.o ./build/release/epr_dump.o ./build/release/epr_typconv.o -lm
ld: symbol dyld_stub_binding_helper not defined (usually in crt1.o/dylib1.o/bundle1.o) for 
inferred architecture x86_64
```

Options used to build are:

```
# for Mac OS X
COMPILE = gcc -fPIC -ansi -c -I$(SRCDIR) -I$(THISDIR) $(OPTIONS)
LINK    = ld -dylib
TARGET  = $(OUTDIR)/libepr_api.dylib
```

I managed to fix the problem adding `/usr/lib/dylib1.o` to the link line of the `makefile`:

```
$(TARGET) : $(OBJECTS)
    $(LINK) -o $@ $(OBJECTS) -lm /usr/lib/dylib1.o
```

instead of:

```
$(TARGET) : $(OBJECTS)
    $(LINK) -o $@ $(OBJECTS) -lm
```

but I don'n know if it is the best way to solve the issue.
